// SPDX-FileCopyrightText: 2026 Devin Brown <devin.kyle.brown@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

//! onyx-daemon — package root aggregating the daemon modules: the SerpentRegistry
//! comptime command system, the CapProof permission lattice, in-process services,
//! OroStore, and the media plane. See docs/architecture/ for the design. The live
//! entry point is `LinuxServer` in `server.zig`, started from `src/main.zig`.

// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const account_verify = @import("account_verify.zig");
pub const acme_cli = @import("acme_cli.zig");
pub const acme_client = @import("acme_client.zig");
pub const acme_http01_listener = @import("acme_http01_listener.zig");
pub const acme_http01_server = @import("acme_http01_server.zig");
pub const acme_renewal = @import("acme_renewal.zig");
pub const acme_runner = @import("acme_runner.zig");
pub const activity_subscriptions = @import("activity_subscriptions.zig");
pub const announce_board = @import("announce_board.zig");
pub const attachment_id = @import("attachment_id.zig");
pub const attachment_delivery_spool = @import("attachment_delivery_spool.zig");
pub const audit_trail = @import("audit_trail.zig");
pub const autojoin = @import("autojoin.zig");
pub const bot_registry = @import("bot_registry.zig");
pub const certfp_bind = @import("certfp_bind.zig");
pub const chanmode = @import("chanmode.zig");
pub const chanstats = @import("chanstats.zig");
pub const client = @import("client.zig");
pub const clone_detect = @import("clone_detect.zig");
pub const clone_limit = @import("clone_limit.zig");
pub const commands = @import("commands.zig");
pub const command_usage = @import("command_usage.zig");
pub const config_boot = @import("config_boot.zig");
pub const config_format = @import("config_format.zig");
pub const conn_class = @import("conn_class.zig");
pub const content_filter = @import("content_filter.zig");
pub const cooldown = @import("cooldown.zig");
pub const cross_shard_smoke = @import("cross_shard_smoke.zig");
pub const deliver_handle = @import("deliver_handle.zig");
pub const dispatch = @import("dispatch.zig");
pub const dlog = @import("dlog.zig");
pub const dnsbl = @import("dnsbl.zig");
pub const dnsbl_resolver = @import("dnsbl_resolver.zig");
pub const dualstack_udp = @import("dualstack_udp.zig");
pub const e2ee_group_dst = @import("e2ee_group_dst.zig");
pub const e2ee_group_mesh_authority = @import("e2ee_group_mesh_authority.zig");
pub const e2ee_group_outbox = @import("e2ee_group_outbox.zig");
pub const e2ee_group_replay_guard = @import("e2ee_group_replay_guard.zig");
pub const event_spine = @import("event_spine.zig");
pub const event_spine_replay_guard = @import("event_spine_replay_guard.zig");
pub const flood_guard = @import("flood_guard.zig");
pub const gag_set = @import("gag_set.zig");
pub const geo_services = @import("geo_services.zig");
pub const guise = @import("guise.zig");
pub const helix = @import("helix/root.zig");
pub const host_request = @import("host_request.zig");
pub const http_fetch = @import("http_fetch.zig");
pub const ip_reputation = @import("ip_reputation.zig");
pub const ktls = @import("ktls.zig");
pub const link_health = @import("link_health.zig");
pub const mail_sender = @import("mail_sender.zig");
pub const media_bridge = @import("media_bridge.zig");
pub const media_plane = @import("media_plane.zig");
pub const media_room = @import("media_room.zig");
pub const memo_group = @import("memo_group.zig");
pub const mesh_clones = @import("mesh_clones.zig");
pub const metrics_http = @import("metrics_http.zig");
pub const webhook = @import("webhook.zig");
pub const webhook_render = @import("webhook_render.zig");
pub const webhook_http = @import("webhook_http.zig");
pub const module_core = @import("module_core.zig");
pub const module_bus = @import("module_bus.zig");
pub const module_lifecycle = @import("module_lifecycle.zig");
pub const module_harness = @import("module_harness.zig");
pub const native_media_link = @import("native_media_link.zig");
pub const native_media_transport = @import("native_media_transport.zig");
pub const netsplit_batch = @import("netsplit_batch.zig");
pub const nick_delay = @import("nick_delay.zig");
pub const nick_enforcement = @import("nick_enforcement.zig");
pub const node_identity = @import("node_identity.zig");
pub const node_keyfile = @import("node_keyfile.zig");
pub const oauth_jwt = @import("oauth_jwt.zig");
pub const observe = @import("observe.zig");
pub const ocsp_staple = @import("ocsp_staple.zig");
pub const operator_groups = @import("operator_groups.zig");
pub const oper = @import("oper.zig");
pub const oper_override = @import("oper_override.zig");
pub const password_reset = @import("password_reset.zig");
pub const poll = @import("poll.zig");
pub const proofmark = @import("proofmark.zig");
pub const proposal = @import("proposal.zig");
pub const rdns = @import("rdns.zig");
pub const reactor_fabric = @import("reactor_fabric.zig");
pub const reactor_pool = @import("reactor_pool.zig");
pub const reactor_wake = @import("reactor_wake.zig");
pub const registry = @import("registry.zig");
pub const relay_v2_event_log = @import("relay_v2_event_log.zig");
pub const relay_v2_replay_guard = @import("relay_v2_replay_guard.zig");
pub const relay_v2_outbox = @import("relay_v2_outbox.zig");
pub const reuseport = @import("reuseport.zig");
pub const s2s_dst = @import("s2s_dst.zig");
pub const s2s_link = @import("s2s_link.zig");
pub const sasl_bridge = @import("sasl_bridge.zig");
pub const scoped_access = @import("scoped_access.zig");
pub const scram_store = @import("scram_store.zig");
pub const search_index = @import("search_index.zig");
pub const secured_s2s_link = @import("secured_s2s_link.zig");
pub const server = @import("server.zig");
pub const server_stats = @import("server_stats.zig");
pub const services = @import("services.zig");
pub const sessions = @import("sessions.zig");
pub const sfu_srtp = @import("sfu_srtp.zig");
pub const shard = @import("shard.zig");
pub const shun = @import("shun.zig");
pub const spamtrap = @import("spamtrap.zig");
pub const stats_report = @import("stats_report.zig");
pub const store = @import("store.zig");
pub const svc_acclist = @import("svc_acclist.zig");
pub const svc_akick = @import("svc_akick.zig");
pub const svc_chanbadwords = @import("svc_chanbadwords.zig");
pub const svc_clonescan = @import("svc_clonescan.zig");
pub const svc_enforce = @import("svc_enforce.zig");
pub const svc_forceaction = @import("svc_forceaction.zig");
pub const svc_jupe = @import("svc_jupe.zig");
pub const svc_lastseen = @import("svc_lastseen.zig");
pub const svc_login_throttle = @import("svc_login_throttle.zig");
pub const svc_masskick = @import("svc_masskick.zig");
pub const svc_memo_forward = @import("svc_memo_forward.zig");
pub const svc_memo_ignore = @import("svc_memo_ignore.zig");
pub const svc_operaudit = @import("svc_operaudit.zig");
pub const svc_recover = @import("svc_recover.zig");
pub const svc_resv = @import("svc_resv.zig");
pub const svc_sessionview = @import("svc_sessionview.zig");
pub const svc_successor = @import("svc_successor.zig");
pub const svc_tempmode = @import("svc_tempmode.zig");
pub const memo = @import("memo.zig");
pub const webpush = @import("webpush.zig");
pub const webauthn_creds = @import("webauthn_creds.zig");
pub const tiered_keys = @import("tiered_keys.zig");
pub const tls_certs = @import("tls_certs.zig");
pub const tls_conn = @import("tls_conn.zig");
pub const tls_sni_load = @import("tls_sni_load.zig");
pub const totp_auth = @import("totp_auth.zig");
pub const transcript = @import("transcript.zig");
pub const warden = @import("warden.zig");
pub const webtransport_listener = @import("webtransport_listener.zig");
pub const welcome_pack = @import("welcome_pack.zig");
pub const whois = @import("whois.zig");
pub const whowas = @import("whowas.zig");
pub const world_projection = @import("world_projection.zig");
pub const world_rcu = @import("world_rcu.zig");
pub const world = @import("world.zig");
// gen:mods:end

// Subsystem packages in subdirectories that genroots does not auto-import
// (modules/ has no root.zig; helix/ is auto-imported by genroots).
pub const module_manifest = @import("modules/manifest.zig");
pub const key_transparency = @import("key_transparency.zig");
/// Standalone DPROP1 codec/state. Exporting it here compiles and tests the leaf
/// module; it does not wire persistence, server runtime, mesh, or authority.
pub const durable_credential_props = @import("durable_credential_props.zig");
pub const durable_credential_props_boot = @import("durable_credential_props_boot.zig");
pub const durable_oper_authority = @import("durable_oper_authority.zig");
pub const durable_oper_authority_boot = @import("durable_oper_authority_boot.zig");
pub const oper_session_provenance = @import("oper_session_provenance.zig");
/// Allocation-free, projection-free coordinator for staged OCG2 observation.
/// The module deliberately exposes no session, mesh, minting, or grant surface.
pub const ocg2_runtime = @import("ocg2_runtime.zig");
/// Transactional, allocation-bounded OCG2 projection queue.  The leaf is
/// exported for the integrator but owns no session, mesh, issuer, or minting
/// capability.
pub const ocg2_projection_runtime = @import("ocg2_projection_runtime.zig");

// Compile the inactive issuer leaf without publishing the module or its Impl.
comptime {
    const issuer = @import("ocg2_authority_issuer.zig");
    _ = issuer.Ocg2AuthorityIssuer;
    if (!@hasDecl(issuer.Ocg2AuthorityIssuer, "executeAuthorized"))
        @compileError("OCG2 issuer must expose executeAuthorized");
    if (@hasDecl(@This(), "ocg2_authority_issuer"))
        @compileError("OCG2 issuer must stay unexported from daemon root");
    for (.{
        "issue",         "grant",       "revoke",
        "issueGrant",    "issueRevoke", "executeGrant",
        "executeRevoke", "transmit",    "executeAuthorized",
    }) |name| {
        if (@hasDecl(issuer, name))
            @compileError("OCG2 issuer must not expose an alternate public issue surface");
    }
}

// Compile the inactive reconcile/expiry schedule leaf without publishing it.
comptime {
    const std = @import("std");
    const schedule = @import("ocg2_reconcile_schedule.zig");
    _ = schedule.build;
    if (@hasDecl(@This(), "ocg2_reconcile_schedule"))
        @compileError("OCG2 reconcile schedule must stay unexported from daemon root");
    const allowed = .{
        "Phase",   "InvalidReason", "ReinspectHint",
        "Summary", "BuildResult",   "build",
    };
    const names = @typeInfo(schedule).@"struct".decl_names;
    if (names.len != allowed.len)
        @compileError("OCG2 reconcile schedule public surface is not the exact allowlist");
    for (names) |name| {
        var found = false;
        for (allowed) |allowed_name| {
            if (std.mem.eql(u8, name, allowed_name)) found = true;
        }
        if (!found)
            @compileError("OCG2 reconcile schedule exposes a public declaration outside the allowlist");
    }
    if (@typeInfo(schedule.ReinspectHint).@"struct".decl_names.len != 0)
        @compileError("ReinspectHint must not expose public methods");
}

// Compile the inactive reconcile workset leaf without publishing it.
comptime {
    const std = @import("std");
    const workset = @import("ocg2_reconcile_workset.zig");
    _ = workset.build;
    if (@hasDecl(@This(), "ocg2_reconcile_workset"))
        @compileError("OCG2 reconcile workset must stay unexported from daemon root");
    const allowed = .{
        "Cause",   "InvalidReason", "BaselineEntry", "WorkItem",
        "Summary", "BuildResult",   "max_entries",   "build",
    };
    const names = @typeInfo(workset).@"struct".decl_names;
    if (names.len != allowed.len)
        @compileError("OCG2 reconcile workset public surface is not the exact allowlist");
    for (names) |name| {
        var found = false;
        for (allowed) |allowed_name| {
            if (std.mem.eql(u8, name, allowed_name)) found = true;
        }
        if (!found)
            @compileError("OCG2 reconcile workset exposes a public declaration outside the allowlist");
    }
    if (@typeInfo(workset.BaselineEntry).@"struct".decl_names.len != 0)
        @compileError("BaselineEntry must not expose public methods");
    if (@typeInfo(workset.WorkItem).@"struct".decl_names.len != 0)
        @compileError("WorkItem must not expose public methods");
    for (.{ workset.BaselineEntry, workset.WorkItem, workset.Summary, workset.BuildResult }) |T| {
        const info = @typeInfo(T);
        switch (info) {
            .@"struct" => |struct_info| {
                for (struct_info.field_types) |field_type| {
                    switch (@typeInfo(field_type)) {
                        .pointer => @compileError("OCG2 workset public structs must not hold pointers or slices"),
                        else => {},
                    }
                }
            },
            .@"union" => |union_info| {
                for (union_info.field_types) |field_type| {
                    switch (@typeInfo(field_type)) {
                        .pointer => @compileError("OCG2 workset public unions must not hold pointers or slices"),
                        else => {},
                    }
                }
            },
            else => {},
        }
    }
    for (.{
        "apply",          "execute",           "grant",
        "revoke",         "mint",              "transmit",
        "session",        "callback",          "Visitor",
        "ProjectionData", "DurableOperLookup", "Services",
        "Store",          "reconcile",         "executeAuthorized",
    }) |name| {
        if (@hasDecl(workset, name))
            @compileError("OCG2 reconcile workset must not expose a runtime privilege surface");
    }
}

// Compile the TEST-ONLY transaction/expiry conformance model without publishing it.
comptime {
    const std = @import("std");
    const dst = @import("ocg2_transaction_dst.zig");
    _ = dst.run;
    _ = dst.step;
    if (@hasDecl(@This(), "ocg2_transaction_dst"))
        @compileError("OCG2 transaction DST must stay unexported from daemon root");
    const allowed = .{
        "Phase", "Input", "Output", "World", "step", "run",
    };
    const names = @typeInfo(dst).@"struct".decl_names;
    if (names.len != allowed.len)
        @compileError("OCG2 transaction DST public surface is not the exact allowlist");
    for (names) |name| {
        var found = false;
        for (allowed) |allowed_name| {
            if (std.mem.eql(u8, name, allowed_name)) found = true;
        }
        if (!found)
            @compileError("OCG2 transaction DST exposes a public declaration outside the allowlist");
    }
    if (@typeInfo(dst.Input).@"struct".decl_names.len != 0)
        @compileError("Input must not expose public methods");
    if (@typeInfo(dst.Output).@"struct".decl_names.len != 0)
        @compileError("Output must not expose public methods");
    if (@typeInfo(dst.World).@"struct".decl_names.len != 0)
        @compileError("World must not expose public methods");
    for (.{ dst.Input, dst.Output, dst.World }) |T| {
        const info = @typeInfo(T);
        switch (info) {
            .@"struct" => |struct_info| {
                for (struct_info.field_types) |field_type| {
                    switch (@typeInfo(field_type)) {
                        .pointer => @compileError("OCG2 transaction DST public structs must not hold pointers or slices"),
                        else => {},
                    }
                }
            },
            else => {},
        }
    }
    for (.{
        "apply",          "execute",           "grant",
        "revoke",         "mint",              "transmit",
        "session",        "callback",          "Visitor",
        "ProjectionData", "DurableOperLookup", "Services",
        "Store",          "reconcile",         "executeAuthorized",
    }) |name| {
        if (@hasDecl(dst, name))
            @compileError("OCG2 transaction DST must not expose a runtime privilege surface");
    }
}

test {
    _ = module_manifest;
    _ = key_transparency;
    _ = durable_credential_props;
    _ = durable_credential_props_boot;
    _ = durable_oper_authority;
    _ = durable_oper_authority_boot;
    _ = oper_session_provenance;
    _ = ocg2_runtime;
    _ = ocg2_projection_runtime;
    _ = @import("ocg2_authority_issuer.zig");
    _ = @import("ocg2_reconcile_schedule.zig");
    _ = @import("ocg2_reconcile_workset.zig");
    _ = @import("ocg2_transaction_dst.zig");
    // gen:tests:begin
    _ = account_verify;
    _ = acme_cli;
    _ = acme_client;
    _ = acme_http01_listener;
    _ = acme_http01_server;
    _ = acme_renewal;
    _ = acme_runner;
    _ = activity_subscriptions;
    _ = announce_board;
    _ = attachment_id;
    _ = attachment_delivery_spool;
    _ = audit_trail;
    _ = autojoin;
    _ = bot_registry;
    _ = certfp_bind;
    _ = chanmode;
    _ = chanstats;
    _ = client;
    _ = clone_detect;
    _ = clone_limit;
    _ = commands;
    _ = command_usage;
    _ = config_boot;
    _ = config_format;
    _ = conn_class;
    _ = content_filter;
    _ = cooldown;
    _ = cross_shard_smoke;
    _ = deliver_handle;
    _ = dispatch;
    _ = dlog;
    _ = dnsbl;
    _ = dnsbl_resolver;
    _ = dualstack_udp;
    _ = e2ee_group_dst;
    _ = e2ee_group_mesh_authority;
    _ = e2ee_group_outbox;
    _ = e2ee_group_replay_guard;
    _ = event_spine;
    _ = event_spine_replay_guard;
    _ = flood_guard;
    _ = gag_set;
    _ = geo_services;
    _ = guise;
    _ = helix;
    _ = host_request;
    _ = http_fetch;
    _ = ip_reputation;
    _ = ktls;
    _ = link_health;
    _ = mail_sender;
    _ = media_bridge;
    _ = media_plane;
    _ = media_room;
    _ = memo_group;
    _ = mesh_clones;
    _ = metrics_http;
    _ = webhook;
    _ = webhook_render;
    _ = webhook_http;
    _ = module_core;
    _ = module_bus;
    _ = module_lifecycle;
    _ = module_harness;
    _ = native_media_link;
    _ = native_media_transport;
    _ = netsplit_batch;
    _ = nick_delay;
    _ = nick_enforcement;
    _ = node_identity;
    _ = node_keyfile;
    _ = oauth_jwt;
    _ = observe;
    _ = ocsp_staple;
    _ = operator_groups;
    _ = oper;
    _ = oper_override;
    _ = password_reset;
    _ = poll;
    _ = proofmark;
    _ = proposal;
    _ = rdns;
    _ = reactor_fabric;
    _ = reactor_pool;
    _ = reactor_wake;
    _ = registry;
    _ = relay_v2_event_log;
    _ = relay_v2_outbox;
    _ = relay_v2_replay_guard;
    _ = reuseport;
    _ = s2s_dst;
    _ = s2s_link;
    _ = sasl_bridge;
    _ = scoped_access;
    _ = scram_store;
    _ = search_index;
    _ = secured_s2s_link;
    _ = server;
    _ = server_stats;
    _ = services;
    _ = sessions;
    _ = sfu_srtp;
    _ = shard;
    _ = shun;
    _ = spamtrap;
    _ = stats_report;
    _ = store;
    _ = svc_acclist;
    _ = svc_akick;
    _ = svc_chanbadwords;
    _ = svc_clonescan;
    _ = svc_enforce;
    _ = svc_forceaction;
    _ = svc_jupe;
    _ = svc_lastseen;
    _ = svc_login_throttle;
    _ = svc_masskick;
    _ = svc_memo_forward;
    _ = svc_memo_ignore;
    _ = svc_operaudit;
    _ = svc_recover;
    _ = svc_resv;
    _ = svc_sessionview;
    _ = svc_successor;
    _ = svc_tempmode;
    _ = memo;
    _ = webpush;
    _ = webauthn_creds;
    _ = tiered_keys;
    _ = tls_certs;
    _ = tls_conn;
    _ = tls_sni_load;
    _ = totp_auth;
    _ = transcript;
    _ = warden;
    _ = webtransport_listener;
    _ = welcome_pack;
    _ = whois;
    _ = whowas;
    _ = world_projection;
    _ = world_rcu;
    _ = world;
    // gen:tests:end
}

test "OCG2ISSUER external import cannot reach identity signer hooks or impl" {
    const std = @import("std");
    const issuer = @import("ocg2_authority_issuer.zig");
    try std.testing.expect(!@hasDecl(@This(), "ocg2_authority_issuer"));
    try std.testing.expect(switch (@typeInfo(issuer.Ocg2AuthorityIssuer)) {
        .@"opaque" => true,
        else => false,
    });
    try std.testing.expect(@hasDecl(issuer.Ocg2AuthorityIssuer, "executeAuthorized"));
    try std.testing.expect(!@hasDecl(issuer, "executeAuthorized"));
    inline for (.{
        "identity",    "services",       "clock",
        "registry",    "mutex",          "poisoned",
        "closed",      "after_allocate", "after_commit",
        "hook_ctx",    "hooks",          "sign_kp",
        "declassify",  "Impl",           "asImpl",
        "testHooks",   "testWipeSigner", "issue",
        "grant",       "revoke",         "issueGrant",
        "issueRevoke", "executeGrant",   "executeRevoke",
        "transmit",
    }) |name| {
        try std.testing.expect(!@hasDecl(issuer.Ocg2AuthorityIssuer, name));
        try std.testing.expect(!@hasDecl(issuer, name));
    }
}

test "OCG2SCHED external import cannot reach apply grant session or export" {
    const std = @import("std");
    const schedule = @import("ocg2_reconcile_schedule.zig");
    try std.testing.expect(!@hasDecl(@This(), "ocg2_reconcile_schedule"));
    const allowed = .{
        "Phase",   "InvalidReason", "ReinspectHint",
        "Summary", "BuildResult",   "build",
    };
    const names = @typeInfo(schedule).@"struct".decl_names;
    try std.testing.expectEqual(@as(usize, allowed.len), names.len);
    inline for (names) |name| {
        var found = false;
        inline for (allowed) |allowed_name| {
            if (std.mem.eql(u8, name, allowed_name)) found = true;
        }
        try std.testing.expect(found);
    }
    try std.testing.expectEqual(@as(usize, 0), @typeInfo(schedule.ReinspectHint).@"struct".decl_names.len);
    try std.testing.expect(!@hasDecl(schedule, "TransactionCopy"));
    try std.testing.expect(!@hasDecl(schedule, "max_account_len"));
    try std.testing.expect(!@hasDecl(schedule, "max_wire_len"));
    try std.testing.expect(!@hasDecl(schedule, "digest_len"));
    try std.testing.expect(!@hasDecl(schedule, "authority_pubkey_len"));
    try std.testing.expect(!@hasDecl(schedule.ReinspectHint, "account"));
    inline for (.{
        "apply",   "execute",        "grant",
        "revoke",  "mint",           "transmit",
        "session", "callback",       "executeAuthorized",
        "issue",   "ProjectionData", "DurableOperLookup",
        "Visitor", "reconcile",      "buildAlloc",
    }) |name| {
        try std.testing.expect(!@hasDecl(schedule, name));
    }
}

test "OCG2WORK external import cannot reach apply grant session or export" {
    const std = @import("std");
    const workset = @import("ocg2_reconcile_workset.zig");
    try std.testing.expect(!@hasDecl(@This(), "ocg2_reconcile_workset"));
    const allowed = .{
        "Cause",   "InvalidReason", "BaselineEntry", "WorkItem",
        "Summary", "BuildResult",   "max_entries",   "build",
    };
    const names = @typeInfo(workset).@"struct".decl_names;
    try std.testing.expectEqual(@as(usize, allowed.len), names.len);
    inline for (names) |name| {
        var found = false;
        inline for (allowed) |allowed_name| {
            if (std.mem.eql(u8, name, allowed_name)) found = true;
        }
        try std.testing.expect(found);
    }
    try std.testing.expectEqual(@as(usize, 0), @typeInfo(workset.BaselineEntry).@"struct".decl_names.len);
    try std.testing.expectEqual(@as(usize, 0), @typeInfo(workset.WorkItem).@"struct".decl_names.len);
    try std.testing.expectEqual(workset.max_entries, @import("durable_oper_authority.zig").max_records);
    try std.testing.expect(!@hasDecl(workset, "Phase"));
    try std.testing.expect(!@hasDecl(workset, "ReinspectHint"));
    try std.testing.expect(!@hasDecl(workset, "TransactionCopy"));
    inline for (@typeInfo(workset.BaselineEntry).@"struct".field_types) |field_type| {
        try std.testing.expect(switch (@typeInfo(field_type)) {
            .pointer => false,
            else => true,
        });
    }
    inline for (@typeInfo(workset.WorkItem).@"struct".field_types) |field_type| {
        try std.testing.expect(switch (@typeInfo(field_type)) {
            .pointer => false,
            else => true,
        });
    }
    inline for (.{
        "apply",          "execute",           "grant",
        "revoke",         "mint",              "transmit",
        "session",        "callback",          "Visitor",
        "ProjectionData", "DurableOperLookup", "Services",
        "Store",          "reconcile",         "executeAuthorized",
    }) |name| {
        try std.testing.expect(!@hasDecl(workset, name));
    }
}

test "S6C6 external import cannot reach runtime privilege surface" {
    const std = @import("std");
    const dst = @import("ocg2_transaction_dst.zig");
    try std.testing.expect(!@hasDecl(@This(), "ocg2_transaction_dst"));
    const allowed = .{
        "Phase", "Input", "Output", "World", "step", "run",
    };
    const names = @typeInfo(dst).@"struct".decl_names;
    try std.testing.expectEqual(@as(usize, allowed.len), names.len);
    inline for (names) |name| {
        var found = false;
        inline for (allowed) |allowed_name| {
            if (std.mem.eql(u8, name, allowed_name)) found = true;
        }
        try std.testing.expect(found);
    }
    try std.testing.expectEqual(@as(usize, 0), @typeInfo(dst.Input).@"struct".decl_names.len);
    try std.testing.expectEqual(@as(usize, 0), @typeInfo(dst.Output).@"struct".decl_names.len);
    try std.testing.expectEqual(@as(usize, 0), @typeInfo(dst.World).@"struct".decl_names.len);
    inline for (@typeInfo(dst.Input).@"struct".field_types) |field_type| {
        try std.testing.expect(switch (@typeInfo(field_type)) {
            .pointer => false,
            else => true,
        });
    }
    inline for (@typeInfo(dst.Output).@"struct".field_types) |field_type| {
        try std.testing.expect(switch (@typeInfo(field_type)) {
            .pointer => false,
            else => true,
        });
    }
    inline for (@typeInfo(dst.World).@"struct".field_types) |field_type| {
        try std.testing.expect(switch (@typeInfo(field_type)) {
            .pointer => false,
            else => true,
        });
    }
    inline for (.{
        "apply",          "execute",           "grant",
        "revoke",         "mint",              "transmit",
        "session",        "callback",          "Visitor",
        "ProjectionData", "DurableOperLookup", "Services",
        "Store",          "reconcile",         "executeAuthorized",
    }) |name| {
        try std.testing.expect(!@hasDecl(dst, name));
    }
}
