// SPDX-FileCopyrightText: 2026 Devin Brown <devin.kyle.brown@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Module-facing stats provider interface — how a SerpentRegistry module
//! contributes a counter or gauge to `/STATS` and to the Prometheus endpoint.
//!
//! Before this existed, every exported metric had to be a hand-written field on
//! `server_stats.Stats` plus a hand-written row in its fixed `rows()` array, so
//! a module could not export anything. A module now declares
//! `stats: []const stats_provider.Spec` and the comptime registry aggregates
//! every module's providers into one flat table (`Live.stats`).
//!
//! Three renderings share that one table so they can never disagree:
//!
//!   * `forEachHuman`      — `conns_active = 5`, the oper `STATS z`/`STATS x` dump.
//!   * `forEachStructured` — `onyx_conns_active{module="core",category="conn",
//!                            kind="gauge"} 5`, machine-readable for scripts.
//!   * `writePrometheus`   — HELP/TYPE/sample exposition text.
//!
//! Reading is pull-based and allocation-free: a provider is a pure function of
//! the host context, called only on the cold render path. The hot path keeps
//! bumping its own atomics (see `server_stats.zig`); a provider just exposes one.
//!
//! Names are validated at COMPILE TIME (see `registry.validate`): a metric name
//! that is not a legal Prometheus identifier, or that collides with another
//! module's, is a build failure — never a corrupt scrape at runtime.
const std = @import("std");

/// Metric semantics. A `counter` only ever increases; a `gauge` moves both ways.
pub const Kind = enum {
    counter,
    gauge,

    pub fn token(self: Kind) []const u8 {
        return @tagName(self);
    }
};

/// Coarse subsystem grouping, so an operator can ask for one slice of the
/// metric surface (`STATS x mesh`) instead of the whole dump.
pub const Category = enum {
    conn,
    traffic,
    reactor,
    tls,
    mesh,
    media,
    security,
    world,
    module,

    pub fn token(self: Category) []const u8 {
        return @tagName(self);
    }
};

/// Provider read function. `ctx` is the erased host context the daemon passes to
/// every module entry point (`*server.LinuxServer` in the live server, exactly
/// like a command handler's or lifecycle fn's ctx). A provider MUST NOT mutate
/// through it, MUST NOT allocate, and MUST NOT block: it runs on the reactor
/// thread that is answering the operator's `STATS`.
///
/// `i128` is wide enough to hold both a `u64` monotonic counter and an `i64`
/// signed gauge without either saturating or wrapping.
pub const ReadFn = *const fn (ctx: *anyopaque) i128;

/// One metric declared by a module.
pub const Spec = struct {
    /// Prometheus metric name. Unique across all modules; must match
    /// `[a-zA-Z_:][a-zA-Z0-9_:]*` (enforced at comptime by `registry.validate`).
    prom: []const u8,
    /// Short token used in the oper `STATS` dump. Unique across all modules;
    /// must match `[a-zA-Z_][a-zA-Z0-9_]*`.
    irc: []const u8,
    /// One-line HELP text for the Prometheus exposition and `STATSPROVIDERS`.
    help: []const u8,
    kind: Kind = .counter,
    category: Category = .module,
    read: ReadFn,
};

/// Immutable stats-table row generated by `registry.Registry`.
pub const Entry = struct {
    module_id: []const u8,
    spec: Spec,
};

/// Longest single rendered line any renderer here emits. The longest form is the
/// structured one: name + module + category + kind labels + a signed 128-bit
/// decimal value. Providers whose rendering would exceed this are skipped rather
/// than truncated (a half-written metric is worse than an absent one).
pub const max_line_len = 512;

/// Whether `name` is a legal Prometheus metric name: `[a-zA-Z_:][a-zA-Z0-9_:]*`.
/// Rejecting at comptime keeps a malformed name from silently corrupting the
/// exposition format (a scrape parse error takes out every metric, not one).
pub fn validPromName(name: []const u8) bool {
    if (name.len == 0) return false;
    for (name, 0..) |c, i| {
        const alpha = (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or c == '_' or c == ':';
        const digit = c >= '0' and c <= '9';
        if (i == 0) {
            if (!alpha) return false;
        } else if (!alpha and !digit) return false;
    }
    return true;
}

/// Whether `token` is a legal short `STATS` token: `[a-zA-Z_][a-zA-Z0-9_]*`.
/// Stricter than `validPromName` (no `:`) because the oper dump renders
/// `token = value` and a colon reads as a namespace separator to scripts.
pub fn validIrcToken(token: []const u8) bool {
    if (token.len == 0) return false;
    for (token, 0..) |c, i| {
        const alpha = (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or c == '_';
        const digit = c >= '0' and c <= '9';
        if (i == 0) {
            if (!alpha) return false;
        } else if (!alpha and !digit) return false;
    }
    return true;
}

/// Emit `irc = value` per provider through `emit`. Never allocates; formats into
/// a stack buffer. `filter` narrows to one category (`null` = every category).
///
/// A provider whose line would overflow `max_line_len` is skipped, not
/// truncated. Renderer errors from `emit` propagate (the caller's send queue
/// filling up must not be swallowed).
pub fn forEachHuman(
    entries: []const Entry,
    ctx: *anyopaque,
    filter: ?Category,
    sink: anytype,
    comptime emit: fn (@TypeOf(sink), []const u8) anyerror!void,
) !void {
    var buf: [max_line_len]u8 = undefined;
    for (entries) |entry| {
        if (filter) |want| {
            if (entry.spec.category != want) continue;
        }
        const value = entry.spec.read(ctx);
        const line = std.fmt.bufPrint(&buf, "{s} = {d}", .{ entry.spec.irc, value }) catch continue;
        try emit(sink, line);
    }
}

/// Emit one machine-readable line per provider through `emit`, in Prometheus
/// sample syntax so a script can parse `/STATS` output with the same code it
/// uses on the metrics endpoint:
///
///     onyx_conns_active{module="core",category="conn",kind="gauge"} 5
///
/// Never allocates. `filter` narrows to one category (`null` = every category).
pub fn forEachStructured(
    entries: []const Entry,
    ctx: *anyopaque,
    filter: ?Category,
    sink: anytype,
    comptime emit: fn (@TypeOf(sink), []const u8) anyerror!void,
) !void {
    var buf: [max_line_len]u8 = undefined;
    for (entries) |entry| {
        if (filter) |want| {
            if (entry.spec.category != want) continue;
        }
        const value = entry.spec.read(ctx);
        const line = std.fmt.bufPrint(&buf, "{s}{{module=\"{s}\",category=\"{s}\",kind=\"{s}\"}} {d}", .{
            entry.spec.prom,
            entry.module_id,
            entry.spec.category.token(),
            entry.spec.kind.token(),
            value,
        }) catch continue;
        try emit(sink, line);
    }
}

/// Append Prometheus exposition text (HELP/TYPE/sample per provider) to `out`.
/// Mirrors `server_stats.Stats.writePrometheus` so module-contributed metrics
/// are indistinguishable from the built-in ones to a scraper.
pub fn writePrometheus(
    entries: []const Entry,
    ctx: *anyopaque,
    allocator: std.mem.Allocator,
    out: *std.ArrayList(u8),
) !void {
    for (entries) |entry| {
        try out.print(allocator, "# HELP {s} {s}\n", .{ entry.spec.prom, entry.spec.help });
        try out.print(allocator, "# TYPE {s} {s}\n", .{ entry.spec.prom, entry.spec.kind.token() });
        try out.print(allocator, "{s} {d}\n", .{ entry.spec.prom, entry.spec.read(ctx) });
    }
}

/// Resolve a category token (`"mesh"`, case-insensitive) to a `Category`.
/// Returns null for an unknown token so the caller can fail closed with a usage
/// reply instead of silently dumping everything.
pub fn categoryFromToken(token: []const u8) ?Category {
    inline for (@typeInfo(Category).@"enum".field_names) |name| {
        if (std.ascii.eqlIgnoreCase(name, token)) return @field(Category, name);
    }
    return null;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

/// Test host context: stands in for `*LinuxServer` as the erased ctx.
const FakeHost = struct {
    conns: i128 = 0,
    peers: i128 = 0,

    fn readConns(ctx: *anyopaque) i128 {
        const self: *FakeHost = @ptrCast(@alignCast(ctx));
        return self.conns;
    }

    fn readPeers(ctx: *anyopaque) i128 {
        const self: *FakeHost = @ptrCast(@alignCast(ctx));
        return self.peers;
    }
};

const fake_entries = [_]Entry{
    .{ .module_id = "core.test", .spec = .{
        .prom = "onyx_test_conns",
        .irc = "t_conns",
        .help = "Test connections",
        .kind = .gauge,
        .category = .conn,
        .read = FakeHost.readConns,
    } },
    .{ .module_id = "mesh.test", .spec = .{
        .prom = "onyx_test_peers",
        .irc = "t_peers",
        .help = "Test peers",
        .kind = .counter,
        .category = .mesh,
        .read = FakeHost.readPeers,
    } },
};

const Collector = struct {
    lines: std.ArrayList([]const u8) = .empty,
    allocator: std.mem.Allocator,

    fn emit(self: *@This(), line: []const u8) anyerror!void {
        // The renderer reuses one stack buffer per iteration, so a collector
        // MUST copy: retaining `line` would dangle on the next iteration.
        try self.lines.append(self.allocator, try self.allocator.dupe(u8, line));
    }

    fn deinit(self: *@This()) void {
        for (self.lines.items) |l| self.allocator.free(l);
        self.lines.deinit(self.allocator);
    }
};

test "human rendering emits one token line per provider, reading live values" {
    var host = FakeHost{ .conns = 7, .peers = 3 };
    var c = Collector{ .allocator = testing.allocator };
    defer c.deinit();

    try forEachHuman(&fake_entries, &host, null, &c, Collector.emit);

    try testing.expectEqual(@as(usize, 2), c.lines.items.len);
    try testing.expectEqualStrings("t_conns = 7", c.lines.items[0]);
    try testing.expectEqualStrings("t_peers = 3", c.lines.items[1]);
}

test "providers are pull-based: a later mutation is reflected on the next render" {
    var host = FakeHost{ .conns = 1 };
    var first = Collector{ .allocator = testing.allocator };
    defer first.deinit();
    try forEachHuman(fake_entries[0..1], &host, null, &first, Collector.emit);
    try testing.expectEqualStrings("t_conns = 1", first.lines.items[0]);

    host.conns = 42;
    var second = Collector{ .allocator = testing.allocator };
    defer second.deinit();
    try forEachHuman(fake_entries[0..1], &host, null, &second, Collector.emit);
    try testing.expectEqualStrings("t_conns = 42", second.lines.items[0]);
}

test "category filter narrows the dump to one subsystem" {
    var host = FakeHost{ .conns = 7, .peers = 3 };
    var c = Collector{ .allocator = testing.allocator };
    defer c.deinit();

    try forEachHuman(&fake_entries, &host, .mesh, &c, Collector.emit);

    try testing.expectEqual(@as(usize, 1), c.lines.items.len);
    try testing.expectEqualStrings("t_peers = 3", c.lines.items[0]);
}

test "structured rendering is Prometheus sample syntax with module and kind labels" {
    var host = FakeHost{ .conns = 7, .peers = 3 };
    var c = Collector{ .allocator = testing.allocator };
    defer c.deinit();

    try forEachStructured(&fake_entries, &host, null, &c, Collector.emit);

    try testing.expectEqualStrings(
        "onyx_test_conns{module=\"core.test\",category=\"conn\",kind=\"gauge\"} 7",
        c.lines.items[0],
    );
    try testing.expectEqualStrings(
        "onyx_test_peers{module=\"mesh.test\",category=\"mesh\",kind=\"counter\"} 3",
        c.lines.items[1],
    );
}

test "prometheus export carries HELP, TYPE, and the sample" {
    var host = FakeHost{ .conns = 5, .peers = 9 };
    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(testing.allocator);

    try writePrometheus(&fake_entries, &host, testing.allocator, &out);

    try testing.expect(std.mem.indexOf(u8, out.items, "# HELP onyx_test_conns Test connections") != null);
    try testing.expect(std.mem.indexOf(u8, out.items, "# TYPE onyx_test_conns gauge") != null);
    try testing.expect(std.mem.indexOf(u8, out.items, "onyx_test_conns 5") != null);
    try testing.expect(std.mem.indexOf(u8, out.items, "# TYPE onyx_test_peers counter") != null);
    try testing.expect(std.mem.indexOf(u8, out.items, "onyx_test_peers 9") != null);
}

test "negative gauge values render signed, not wrapped" {
    const Neg = struct {
        fn read(_: *anyopaque) i128 {
            return -5;
        }
    };
    const entries = [_]Entry{.{ .module_id = "m", .spec = .{
        .prom = "onyx_neg",
        .irc = "neg",
        .help = "h",
        .kind = .gauge,
        .read = Neg.read,
    } }};
    var host = FakeHost{};
    var c = Collector{ .allocator = testing.allocator };
    defer c.deinit();
    try forEachHuman(&entries, &host, null, &c, Collector.emit);
    try testing.expectEqualStrings("neg = -5", c.lines.items[0]);
}

test "prometheus and irc name validators accept legal names and reject malformed ones" {
    try testing.expect(validPromName("onyx_conns_total"));
    try testing.expect(validPromName("_leading_underscore"));
    try testing.expect(validPromName("ns:metric"));
    try testing.expect(!validPromName(""));
    try testing.expect(!validPromName("0starts_with_digit"));
    try testing.expect(!validPromName("has space"));
    try testing.expect(!validPromName("has-dash"));
    try testing.expect(!validPromName("has\"quote"));
    try testing.expect(!validPromName("has{brace"));
    try testing.expect(!validPromName("has\nnewline"));

    try testing.expect(validIrcToken("conns_active"));
    try testing.expect(!validIrcToken(""));
    try testing.expect(!validIrcToken("has space"));
    // A colon is legal in Prometheus but not in the `token = value` oper dump.
    try testing.expect(!validIrcToken("ns:metric"));
}

test "category token resolution is case-insensitive and fails closed on garbage" {
    try testing.expectEqual(Category.mesh, categoryFromToken("mesh").?);
    try testing.expectEqual(Category.mesh, categoryFromToken("MESH").?);
    try testing.expectEqual(Category.reactor, categoryFromToken("Reactor").?);
    try testing.expect(categoryFromToken("nosuchcategory") == null);
    try testing.expect(categoryFromToken("") == null);
}

test "an over-long provider line is skipped rather than truncated" {
    const Big = struct {
        fn read(_: *anyopaque) i128 {
            return 1;
        }
    };
    // An irc token longer than the render buffer cannot produce a valid line.
    const token_buf: [max_line_len + 8]u8 = @splat('x');
    const entries = [_]Entry{
        .{ .module_id = "m", .spec = .{
            .prom = "onyx_ok",
            .irc = "ok",
            .help = "h",
            .read = Big.read,
        } },
        .{ .module_id = "m", .spec = .{
            .prom = "onyx_too_long",
            .irc = &token_buf,
            .help = "h",
            .read = Big.read,
        } },
    };
    var host = FakeHost{};
    var c = Collector{ .allocator = testing.allocator };
    defer c.deinit();
    try forEachHuman(&entries, &host, null, &c, Collector.emit);
    // Only the well-formed provider rendered; the oversized one was dropped.
    try testing.expectEqual(@as(usize, 1), c.lines.items.len);
    try testing.expectEqualStrings("ok = 1", c.lines.items[0]);
}
